### ISSUE TITLE
Maximum update depth exceed

### ISSUE THREAD

**Issue by fabiokounang** [janevalencia/hip-eats#14]
![image](https://user-images.githubusercontent.com/31584818/194208874-4148bdb4-77e6-4845-87d4-62c86ad9acb6.png)

Jane, found a warning, maybe it can decrease your app performance, it keeps increasing until 10000++.
But anyway nice apps !!! Keep it up !

**Comment by janevalencia** [comment]
Thanks @fabiokounang and nice catch btw! and yes, it is an uncaught infinite loop 🌀 Fix is coming soon 👍
